[package]
name = "secrets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.11", features = ["derive"] }
requestty = { version = "0.5.0", features = ["macro", "macros"] }
serde = { version = "1.0.169", features = ["derive"] }
serde_json = "1.0.100"
sqlite = "0.31.0"
